### ISSUE TITLE
July 28 ArtWalk Plan

### ISSUE THREAD

**Issue by zee-em** [zee-em/saw-program#1]
How can SAW participate in ArtWalk on July 28? 
What's the best set of demos, activities, music, and displays to lure community into the space? 

GOAL: Increase evening class sign-ups and community awareness of SAW

Tasks to complete
- [ ] select ArtWalk planner/coordinator/host (two different people)
- [ ] plan a small show/display
- [ ] plan a demo
- [ ] create flyers for event, ensure that materials are available for
- [ ] get music/DJ (Don?)
- [ ] get some food/drink
- [ ] create comms plan

**Comment by hutchowen** [comment]
NO ARTWALK IN JULY. WHEW!

**Comment by zee-em** [comment]
Should we do Artwalk in August instead?

**Comment by hutchowen** [comment]
Yes, with James Turek maybe? Good idea...?
